Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Setting__mdt/Setting__mdt.object-meta.xml
<CustomObject>
    <label>Setting</label>
    <pluralLabel>Settings</pluralLabel>
</CustomObject>

Property Management System/force-app/main/default/objects/Setting__mdt/fields/FetchFromStaticResource__c.field-meta.xml
<CustomField>
    <fullName>FetchFromStaticResource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FetchFromStaticResource</label>
    <type>Checkbox</type>
</CustomField>

Property Management System/force-app/main/default/classes/NativeEngineTest.cls
/************************************************************************************************************************************
Author 		: 	Shahaji Mahakale
Description :   This test class is used to cover scenarios of apex class NativeEngine.
History		:
----------------------------------------------------------------------------------------------------------------------------------
VERSION		DATE				AUTHOR					DETAIL
1	 	    20/11/2019		    Shahaji Mahakale       Initial Development
**************************************************************************************************************************************/
@isTest
public class NativeEngineTest {
    @isTest
    static void saveRecord(){
        Result result = new Result(false);
        List<Object> lstOfJsonObject = TestDataFactory.createJSONObjectsForInsert();
        sObject newObject = TestDataFactory.createDatasource();
        boolean isNameSpace;
       
        try{
            isNameSpace = userinfo.isCurrentUserLicensed('epms');
        }
        catch (exception ex){
            System.debug('Exception ' + ex);
            isNameSpace = false;
        }
        if(true){     
            if(isNameSpace){
            
            	result = NativeEngine.saveRecord(lstOfJsonObject, 'epms__Reservation__c', 'PMS_Manage_Package', 'passthrough', newObject);

            }
            else{
			
				result = NativeEngine.saveRecord(lstOfJsonObject, 'Reservation__c', 'PMS_Manage_Package', 'passthrough', newObject);

            }
        }
        
        System.assert(result != null);
    } 
    
        @isTest
    static void saveRecordReturnNull(){
        Result result = new Result(false);
        List<Object> lstOfJsonObject = TestDataFactory.createJSONObjectsForInsert();
        sObject newObject = TestDataFactory.createDatasource();
        boolean isNameSpace;
       
        try{
            isNameSpace = userinfo.isCurrentUserLicensed('epms');
        }
        catch (exception ex){
            System.debug('Exception ' + ex);
            isNameSpace = false;
        }
        if(true){     
            if(isNameSpace){
            
            	result = NativeEngine.saveRecord(lstOfJsonObject, '', 'PMS_Manage_Package', 'passthrough', newObject);
              
                 System.assert(result == null);
            }
            else{
			
				result = NativeEngine.saveRecord(lstOfJsonObject, '', 'PMS_Manage_Package', 'passthrough', newObject);
                System.assert(result == null);
               

            }
        }
       
       
    } 
    
    
    @isTest
    static void removeRecord(){
        Result result = new Result(false);
        List<Object> lstOfJsonObject = TestDataFactory.createJSONObjectsForInsert();
        system.debug('lstOfJsonObject: '+lstOfJsonObject);
        sObject newObject = TestDataFactory.createDatasource();
        //Setting__mdt setting =  TestDataFactory.getSetting();
       // Organization objOrganization = [SELECT NamespacePrefix FROM Organization];
        //if(setting != null && setting.FetchFromStaticResource__c){
            boolean isNameSpace =false;
            try{
                 isNameSpace = userinfo.isCurrentUserLicensed('epms');
            }
            catch (exception ex){
                System.debug('Exception ' + ex);
                isNameSpace = false;
            }
        if(true){
           if(isNameSpace){
            	result = NativeEngine.removeRecord(lstOfJsonObject, 'epms__Reservation__c', 'PMS_Manage_Package', 'passthrough', newObject);
                 
           }
            else{
				result = NativeEngine.removeRecord(lstOfJsonObject, 'Reservation__c', 'PMS_Manage_Package', 'passthrough', newObject);
            }
        }
        System.assert(result != null);
   }
     
    @isTest
    static void removeRecordReturnNull(){
        Result result = new Result(false);
        List<Object> lstOfJsonObject = TestDataFactory.createJSONObjectsForInsert();
        system.debug('lstOfJsonObject: '+lstOfJsonObject);
        sObject newObject = TestDataFactory.createDatasource();
        //Setting__mdt setting =  TestDataFactory.getSetting();
       // Organization objOrganization = [SELECT NamespacePrefix FROM Organization];
        //if(setting != null && setting.FetchFromStaticResource__c){
            boolean isNameSpace =false;
            try{
                 isNameSpace = userinfo.isCurrentUserLicensed('epms');
            }
            catch (exception ex){
                System.debug('Exception ' + ex);
                isNameSpace = false;
            }
        if(true){
           if(isNameSpace){
            	result = NativeEngine.removeRecord(lstOfJsonObject, '', 'PMS_Manage_Package', 'passthrough', newObject);
                               System.assert(result == null);
          
            }
            else{
				result = NativeEngine.removeRecord(lstOfJsonObject, '', 'PMS_Manage_Package', 'passthrough', newObject);
                System.assert(result == null);
            }
        }
      
   }

    @isTest
    static void query(){
        Result result = new Result(false);
        List<Object> lstOfJsonObject = TestDataFactory.createJSONObjectsForInsert();
        sObject newObject = TestDataFactory.createDatasource();
        ModelWrapper objQuery = TestDataFactory.createQuery();
   		ModelWrapper modelInfo = TestDataFactory.createStaticResource('Reservations');
        
        result = NativeEngine.query(objQuery.conditions, modelInfo.name, 'PMS_Manage_Package', newObject);
        System.assert(result != null);
        result = NativeEngine.query(objQuery.conditions, 'Reservation__c', '', null, null, 'PMS_Manage_Package', 'passthrough', newObject);
        System.assert(result != null); 
    }
       
      @isTest
    static void queryWithNofields(){
        Result result = new Result(false);
        List<Object> lstOfJsonObject = TestDataFactory.createJSONObjectsForInsert();
        sObject newObject = TestDataFactory.createDatasource();
        ModelWrapper objQuery = TestDataFactory.createQuery();
   		ModelWrapper modelInfo = TestDataFactory.createStaticResource('Reservations');
        
        result = NativeEngine.query(objQuery.conditions, modelInfo.name, 'PMS_Manage_Package', newObject);
        System.assert(result != null);
        result = NativeEngine.query(objQuery.conditions, 'Reservation__c', 'Name', null, null, 'PMS_Manage_Package', null, newObject);
        System.assert(result != null);
    }
  
}