Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason__c</fullName>
    <label>Other Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Partially Checked In</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrReservationUpdateUTROnCancel.cls
public class TrReservationUpdateUTROnCancel implements Callable{
    public Object call(String action, Map<String, Object> mapOldAndNewRecords) {
        updateUTROnCancelReservation( (List<sObject>)mapOldAndNewRecords.get('lstNewRecords'), (Map<Id, sObject>)mapOldAndNewRecords.get('mapOldRecords'));
        return null;
    }
    
    public void updateUTROnCancelReservation(List<Reservation__c> lstReservations, Map<Id, SObject> mapOldReservations){
        Set<Id> setReservationIds = new Set<Id>();
        for(Reservation__c objReservation: lstReservations){
            Reservation__c objOldReservation = (Reservation__c)mapOldReservations.get(objReservation.Id);
            if(objReservation.Action__c == 'Cancel Reservation' && objReservation.Cancellation_Reason__c == Null){
                objReservation.addError('You cannot cancel reservation without cancellation reason');
            }else if(objReservation.Action__c == 'Cancel Reservation' && objReservation.Cancellation_Reason__c != objOldReservation.Cancellation_Reason__c){
                setReservationIds.add(objReservation.Id);
            }
        }
        List<Unit_Type_Reservation__c> lstUTRToUpdate = new List<Unit_Type_Reservation__c>();
        for(Unit_Type_Reservation__c objUTR: [SELECT Id ,Name, Action__c, Cancellation_Reason__c, Other_Reason__c, Reservation__c, Status__c, Unit_Type__c, Unit__c FROM Unit_Type_Reservation__c WHERE Reservation__c IN: setReservationIds WITH SECURITY_ENFORCED]){
            if(Schema.sObjectType.Unit_Type_Reservation__c.fields.Cancellation_Reason__c.isUpdateable()){
                objUTR.Cancellation_Reason__c = 'Reservation Cancelled';
            }
            if(Schema.sObjectType.Unit_Type_Reservation__c.fields.Status__c.isUpdateable()){
                objUTR.Status__c = 'Cancelled';
            }
            lstUTRToUpdate.add(objUTR);
        }
        if(!lstUTRToUpdate.isEmpty() && Schema.sObjectType.Unit_Type_Reservation__c.isUpdateable()){
            Update lstUTRToUpdate;
        }
    }
}