force-app/main/default/objects/Candidate_Rasika__c/Candidate_Rasika__c.object-meta.xml
<CustomObject>
    <label>Candidate_Rasika</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates_Rasika</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Rasika__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Rasika__c/fields/Job_Rasika__c.field-meta.xml
<CustomField>
    <fullName>Job_Rasika__c</fullName>
    <label>Job_Rasika</label>
    <referenceTo>Job_Rasika__c</referenceTo>
    <relationshipLabel>Candidates_Rasika</relationshipLabel>
    <relationshipName>Candidates_Rasika</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Rasika__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Rasika__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/Job_Rasika__c.object-meta.xml
<CustomObject>
    <label>Job_Rasika</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jobs_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs_Rasika</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Rasika__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <label>Certification Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMP (Project Management Professional)</fullName>
            </value>
            <value>
                <fullName>CMP (Certified Project Manager)</fullName>
            </value>
            <value>
                <fullName>MPM (Master Project Manager)</fullName>
            </value>
            <value>
                <fullName>Sun Certified</fullName>
            </value>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Sybase</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>RedHat</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs_Rasika</relationshipLabel>
    <relationshipName>Jobs_Rasika</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Qualifications_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualifications_Required__c</fullName>
    <label>Qualifications Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>B.A.</fullName>
            </value>
            <value>
                <fullName>B.Com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>Team Player</fullName>
            </value>
            <value>
                <fullName>Self Management</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/recordTypes/Manager.recordType-meta.xml
<RecordType>
    <fullName>Manager</fullName>
    <active>true</active>
    <label>Manager</label>
</RecordType>

force-app/main/default/classes/test_method.cls
@isTest
public class test_method {
    @isTest static void expected_salary(){
        List<Candidate_Rasika__c> can = new List<Candidate_Rasika__c>();
        Candidate_Rasika__c c1 = new Candidate_Rasika__c(First_Name__c='fname',Last_Name__c = 'lname', email__c = 'rsk@gmail.com', status__c = 'Hired', Job_Rasika__c='a0B2w000001hhYuEAI');
        can.add(c1);
        Test.startTest();
        try{insert can;}
        catch(Exception ee){}
    	Test.stopTest();
    }
    @isTest static void inactiveJOb(){
        List<Candidate_Rasika__c> can = new List<Candidate_Rasika__c>();
        Candidate_Rasika__c c1 = new Candidate_Rasika__c(First_Name__c='fname',Last_Name__c = 'lname', email__c = 'rsk@gmail.com', status__c = 'Hired', Job_Rasika__c='a0B2w000001hhZT');
        can.add(c1);
        Test.startTest();
        try{insert can;}
        catch(Exception ee){}
    	Test.stopTest();
    }
    @isTest static void applicationDate(){
        List<Candidate_Rasika__c> can = new List<Candidate_Rasika__c>();
        Candidate_Rasika__c c1 = new Candidate_Rasika__c(First_Name__c='fname',Last_Name__c = 'lname', email__c = 'rsk@gmail.com', status__c = 'Hired', Job_Rasika__c='a0B2w000001hhZT', Application_Date__c = Date.parse('09/20/2020'));
        can.add(c1);
        Test.startTest();
        try{insert can;}
        catch(Exception ee){}
        c1.Application_Date__c = Date.parse('09/25/2020');
    	Test.stopTest();
    }
    @isTest static void cannotDeleteActiveJob(){
        List<Job_Rasika__c> jb = new List<Job_Rasika__c>();
        Job_Rasika__c j1 = new Job_Rasika__c(Number_of_Positions__c = 2, Manager__c = '0032w00000JBmQM', Required_Skills__c = 'Team Player', Certification_Required__c = '(MPM) Master Project Manager', Qualifications_Required__c='MBA', Active__c = true);
        jb.add(j1);
        Test.startTest();
        try{insert jb;
           delete(jb);}
        catch(Exception ee){}
    	Test.stopTest();
    }
    @isTest static void activeFalse(){
        Job_Rasika__c j2 = new Job_Rasika__c();
        j2.id = 'a0B2w000001hf1b';
        Test.startTest();
       	j2.Number_of_Positions__c = 0;
    	Test.stopTest();
    }
    @isTest static void activeTrue(){
        Job_Rasika__c j3 = new Job_Rasika__c();
        j3.id = 'a0B2w000001hhLy';
        Test.startTest();
       	j3.Number_of_Positions__c = 0;
    	Test.stopTest();
    }
}