force-app/main/default/objects/Candidate_Rasika__c/Candidate_Rasika__c.object-meta.xml
<CustomObject>
    <label>Candidate_Rasika</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates_Rasika</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Rasika__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PMS/force-app/main/default/classes/CandidateFutureApexSendEmail.cls
/********************************************************************** 
Name: CandidateFutureApexSendEmail
sendemail
Copyright © 2009 Enzigma Software Pvt Ltd. 
====================================================== 
====================================================== 
Purpose: Send email to candidate with PDF attachement
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Name 25/09/2020 INITIAL DEVELOPMENT 
***********************************************************************/
public class CandidateFutureApexSendEmail {
    
    @future(callout=true)
    public static void SendToCandidate(String cId, String emailId) {
                 
    	//for(Candidate_Rasika__c c: cnd){
            //if(c.Status__c == 'HIRED'){
                
            try{
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       			Messaging.EmailFileAttachment attachPdf = new Messaging.EmailFileAttachment();
       	
       			PageReference pref = page.CandidateDetailPDF;
				pref.getParameters().put('id',cId);
				pref.setRedirect(true);
				Blob b = pref.getContent();
				attachPdf.setFileName('CandidateDetailPDF.pdf');
				attachPdf.setBody(b);
           
       			String[] toAddresses = new String[] {emailId};
       			mail.setToAddresses(toAddresses);
       			mail.setSubject('Regarding Job Offer'); 
       			mail.setPlainTextBody('Congratulation !!!');
        
       			mail.setFileAttachments(new Messaging.EmailFileAttachment[] {attachPdf});
       			Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
       			inspectResults(results);
            }
            catch(Exception ee){}
            //}
    	//}
    }
    private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
       Boolean sendResult = true;
       for (Messaging.SendEmailResult res : results) {
           if (res.isSuccess()) {
               System.debug('Email sent successfully');
           }
           else {
               sendResult = false;
               System.debug('The following errors occurred: ' + res.getErrors());                
           }
       }
       return sendResult;
   }
}