force-app/main/default/objects/Candidate_Rasika__c/Candidate_Rasika__c.object-meta.xml
<CustomObject>
    <label>Candidate_Rasika</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates_Rasika</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Rasika__c/fields/Job_Rasika__c.field-meta.xml
<CustomField>
    <fullName>Job_Rasika__c</fullName>
    <label>Job_Rasika</label>
    <referenceTo>Job_Rasika__c</referenceTo>
    <relationshipLabel>Candidates_Rasika</relationshipLabel>
    <relationshipName>Candidates_Rasika</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/Job_Rasika__c.object-meta.xml
<CustomObject>
    <label>Job_Rasika</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jobs_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs_Rasika</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CandidateTriggerHelper.cls
public class CandidateTriggerHelper {
    /*List<Job_Rasika__c> job{get; set;}
public static void checkJobStatus(List<Candidate_Rasika__c> candidates)
{
    Map<String,Job_Rasika__c> jobMap=new Map<String ,Job_Rasika__c>([SELECT  id,Name,Active_status__c FROM Job_Rasika__c
                                                                         WHERE Active_status__c!=true ]);
    for(Candidate_Rasika__c candidate: candidates)
    {
        
        
    }        
        
}*/
}