force-app/main/default/objects/Candidate_Rasika__c/Candidate_Rasika__c.object-meta.xml
<CustomObject>
    <label>Candidate_Rasika</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates_Rasika</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Rasika__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TEXT( Salutation__c )    &amp; &quot; &quot;  &amp;  First_Name__c  &amp; &quot; &quot;  &amp;  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate_Rasika__c/fields/Job_Rasika__c.field-meta.xml
<CustomField>
    <fullName>Job_Rasika__c</fullName>
    <label>Job_Rasika</label>
    <referenceTo>Job_Rasika__c</referenceTo>
    <relationshipLabel>Candidates_Rasika</relationshipLabel>
    <relationshipName>Candidates_Rasika</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Candidate_Rasika__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/Job_Rasika__c.object-meta.xml
<CustomObject>
    <label>Job_Rasika</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jobs_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs_Rasika</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Rasika__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <label>Certification Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMP (Project Management Professional)</fullName>
            </value>
            <value>
                <fullName>CMP (Certified Project Manager)</fullName>
            </value>
            <value>
                <fullName>MPM (Master Project Manager)</fullName>
            </value>
            <value>
                <fullName>Sun Certified</fullName>
            </value>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Sybase</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>RedHat</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs_Rasika</relationshipLabel>
    <relationshipName>Jobs_Rasika</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Qualifications_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualifications_Required__c</fullName>
    <label>Qualifications Required</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>B.A.</fullName>
            </value>
            <value>
                <fullName>B.Com</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required Skills</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>Team Player</fullName>
            </value>
            <value>
                <fullName>Self Management</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/recordTypes/Manager.recordType-meta.xml
<RecordType>
    <fullName>Manager</fullName>
    <active>true</active>
    <label>Manager</label>
</RecordType>

force-app/main/default/classes/ViewJob.cls
/********************************************************************** 
Name: ViewJob
Copyright © 2009 Enzigma Software Pvt Ltd. 
====================================================== 
====================================================== 
Purpose: To view job details and related candidates details
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Name 08/09/2020 INITIAL DEVELOPMENT 
***********************************************************************/
public class ViewJob {
    
    public List<Job_Rasika__c> job{get;set;}
    public List<Candidate_Rasika__c> candidate{get;set;}
    public List<String> jobRecords{get;set;}
    public List<String> candidateRecords{get;set;}
    
    //Method to view job and candidates details
    public ViewJob(){
        
        String Id = ApexPages.currentPage().getParameters().get('id');
        jobRecords = new List<String>{'Name', 'Description', 'No_of_positions', 'Manager', 'Required_Skills', 'Certification_Required',
            						'Qualifications_Required'};
        job=[Select Name,Description__c,Number_of_positions__c,Manager__c,Required_skills__c,Certification_Required__c,
             Qualifications_Required__c , (Select Name, Full_Name__c, Email__c, Status__c FROM Candidates_Rasika__r)
 			 FROM Job_Rasika__c WHERE Id =: Id];
        
        candidateRecords = new List<String>{'Name', 'Full_Name', 'Email', 'Status'};
        candidate = job[0].Candidates_Rasika__r;
    }
}