force-app/main/default/objects/Candidate_Rasika__c/Candidate_Rasika__c.object-meta.xml
<CustomObject>
    <label>Candidate_Rasika</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates_Rasika</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Rasika__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <label>Expected Salary</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate_Rasika__c/fields/Job_Rasika__c.field-meta.xml
<CustomField>
    <fullName>Job_Rasika__c</fullName>
    <label>Job_Rasika</label>
    <referenceTo>Job_Rasika__c</referenceTo>
    <relationshipLabel>Candidates_Rasika</relationshipLabel>
    <relationshipName>Candidates_Rasika</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/Job_Rasika__c.object-meta.xml
<CustomObject>
    <label>Job_Rasika</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jobs_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs_Rasika</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Rasika__c/fields/Hired_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Hired_Applicants__c</fullName>
    <description>This field indicates the count of the total Hired candidate has applied to this job</description>
    <label>Hired Applicants</label>
    <summaryFilterItems>
        <field>Candidate_Rasika__c.Status__c</field>
        <operation>equals</operation>
        <value>&quot;Hired&quot;</value>
    </summaryFilterItems>
    <summaryForeignKey>Candidate_Rasika__c.Job_Rasika__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Rasika__c/recordTypes/Manager.recordType-meta.xml
<RecordType>
    <fullName>Manager</fullName>
    <active>true</active>
    <label>Manager</label>
</RecordType>

force-app/main/default/classes/TriggerHelperClass.cls
/********************************************************************** 
Name: TriggerHelperClass
Copyright © 2009 Enzigma Software Pvt Ltd. 
====================================================== 
====================================================== 
Purpose: Helper class for JobTrigger and CandidateTrigger
------- 
====================================================== 
====================================================== 
History 
-------
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Name 10/09/2020 INITIAL DEVELOPMENT 
***********************************************************************/
public class TriggerHelperClass {
    
    /*******************************************************************
	Purpose: Send email to manager
	********************************************************************/
	public static void sendMail(String address, String subject, String body) {
       Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       String[] toAddresses = new String[] {address};
       mail.setToAddresses(toAddresses);
       mail.setSubject(subject);
       mail.setPlainTextBody(body);
       Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
       inspectResults(results);
       System.debug('email sending');
   }
   //check status of email
   private static Boolean inspectResults(Messaging.SendEmailResult[] results) {
       Boolean sendResult = true;
       for (Messaging.SendEmailResult res : results) {
           if (res.isSuccess()) {
               System.debug('Email sent successfully');
           }
           else {
               sendResult = false;
               System.debug('The following errors occurred: ' + res.getErrors());                
           }
       }
       return sendResult;
   }
    
    /*******************************************************************
	Purpose: Active job cannot be deleted
	********************************************************************/
    public static void isJobActive(List<Job_Rasika__c> jobList){
        for(Job_Rasika__c job: jobList){
        	if(job.Active__c == True){
        		job.addError('Trigger error: This Job is active and can not be deleted');
        	}
        }
    }
    
    /*******************************************************************
	Purpose: Deactivate job when no.of positions are equal to hired candidates
	********************************************************************/
    public static void isHired(List<Job_Rasika__c> jobList){
        for(Job_Rasika__c job: jobList){
        	if(job.Number_of_Positions__c == job.Hired_Applicants__c){
                if(job.Active__c == true){
                	job.Active__c = false;
                }
            }
        }
    }
    
    /*******************************************************************
	Purpose: Activate job when no.of positions are more than hired candidates
	********************************************************************/
    public static void activateJob(List<Job_Rasika__c> jobList){
        for(Job_Rasika__c job: jobList){
            if(job.Number_of_Positions__c > job.Hired_Applicants__c){
                if(job.Active__c == false){
                	job.Active__c = true;
                }
            }
        }
    }
    
    /*******************************************************************
	Purpose: Expected salary missing error
	********************************************************************/
    public static void expectedSalary(List<Candidate_Rasika__c> cndList){
        for(Candidate_Rasika__c c: cndList){
        	if(c.Expected_Salary__c == null){
            	c.addError('Test-method: Trigger error: Expected Salary field is missing');
            }
        }
    }
    
    /*******************************************************************
	Purpose: Cannot apply to inactive job
	********************************************************************/
    public static void applyInactiveJob(List<Candidate_Rasika__c> cndList){
        Map<String, Job_Rasika__c> jobMap = new Map<String, Job_Rasika__c>([SELECT Id, Active__c from Job_Rasika__c]);
        List<Job_Rasika__c> jobList=jobMap.values();
        //System.debug('List: '+jobList);
        for(Candidate_Rasika__c c: cndList){
        	if(!jobMap.get(c.Job_Rasika__c).Active__c){
            	c.addError('Trigger error: This Job is not active. You can not apply for this job');
            }  
        }
    }
    
    /*******************************************************************
	Purpose: Cannot modify application date
	********************************************************************/
    public static void applicationDate(List<Candidate_Rasika__c> oldList, List<Candidate_Rasika__c> newList){
        for(Candidate_Rasika__c oldDate: oldList){
        	for(Candidate_Rasika__c newDate: newList){
            	if(oldDate.Id == newDate.Id && oldDate.Application_Date__c != newDate.Application_Date__c){
                	newDate.addError('Trigger error: Application date cannot be changed');
                }
            }
        }
    }
    
    /*******************************************************************
	Purpose: Delete candidate if Expected_Salary__c >=100000
	********************************************************************/
   	public static void deleteCandidate()
    {
         List<Candidate_Rasika__c> cnd=[SELECT ID from Candidate_Rasika__c where Expected_Salary__c >=100000];
         delete cnd;
    }
}