Property Management System/force-app/main/default/objects/Service_Interruption__c/Service_Interruption__c.object-meta.xml
<CustomObject>
    <label>Service Interruption</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Interruption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Interruptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Completed</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Interruption_Reason__c.field-meta.xml
<CustomField>
    <fullName>Interruption_Reason__c</fullName>
    <label>Interruption Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Water Leakage</fullName>
            </value>
            <value>
                <fullName>Electricity Fitting</fullName>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Wiring</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Service Interruptions</relationshipLabel>
    <relationshipName>Service_Interruptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type__c/fields/Units_Available__c.field-meta.xml
<CustomField>
    <fullName>Units_Available__c</fullName>
    <label>Units Available</label>
    <summaryForeignKey>Unit__c.Unit_Type__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrUpdateService_Interruption.cls
public with sharing class TrUpdateService_Interruption implements Callable{    
    public Object call(String action, Map<String, Object> mapOldAndNewRecords) {
        validateRecord( (List<sObject>)mapOldAndNewRecords.get('lstNewRecords') ,(Map<Id, sObject>)mapOldAndNewRecords.get('mapOldRecords'));
        return null;
    }
    
    public void validateRecord(List<Service_Interruption__c> lstNewServiceInterruption, Map<Id, sObject> mapOldRecords){
        List<Id> lstUnitIds = new List<Id>();
        List<Id> lstServiceInterruptionIds = new List<Id>();
        TrCreateService_Interruption objTrCreateServiceInterruption = new TrCreateService_Interruption();
        
        for(Service_Interruption__c serviceInterruptionRec : lstNewServiceInterruption){
            if(serviceInterruptionRec.Start_Date__c != NULL && serviceInterruptionRec.End_Date__c != NULL){
          
                if(serviceInterruptionRec.Start_Date__c > serviceInterruptionRec.End_Date__c){
                    serviceInterruptionRec.addError(System.label.EndDateShouldBeGreaterThenStartDate);
                    break;
                } 
                else if(serviceInterruptionRec.End_Date__c < system.today()){
                    serviceInterruptionRec.addError(System.label.EndDateShouldBeGreaterThenStartDate);  
                 }
                if(serviceInterruptionRec.Unit__c != NULL){
                    lstUnitIds.add(serviceInterruptionRec.Unit__c);
                    lstServiceInterruptionIds.add(serviceInterruptionRec.Id);
                }
            }
            else{
            	serviceInterruptionRec.addError(System.Label.PleaseCheckStartDateAndEndDate);
            }
            if(serviceInterruptionRec.Action__c == 'Cancel Interruption' && serviceInterruptionRec.Cancellation_Reason__c == Null){
                    serviceInterruptionRec.addError(System.Label.Can_t_cancel_service_interruption);
            }
            if(String.isEmpty(serviceInterruptionRec.Cancellation_Reason__c) && !String.isEmpty(serviceInterruptionRec.Interruption_Reason__c) && serviceInterruptionRec.Interruption_Reason__c.toLowerCase() != 'other'){
                serviceInterruptionRec.Other_Reason__c = null;
                 lstServiceInterruptionIds.add(serviceInterruptionRec.Id);                
            }
        }
    	Set<Id> setUnitTypeIds = new Set<Id>();
        List<Unit__c> lstUnitTypeIds = [SELECT Id, Unit_Type__c FROM Unit__c WHERE Id IN : lstUnitIds];
        Map<Id, Id> mapUnitIdsToUnitTypeId = new Map<Id, Id>();
        for(Unit__c objUnits: lstUnitTypeIds){
            setUnitTypeIds.add(objUnits.Unit_Type__c);
            mapUnitIdsToUnitTypeId.put(objUnits.Id, objUnits.Unit_Type__c);
        }
    	System.debug('setUnitTypeIds in update: '+setUnitTypeIds);
        List<Service_Interruption__c> lstOldServiceInterruption = [SELECT Id, Start_Date__c, End_Date__c, Unit__c, Unit__r.Unit_Type__c,Action__c FROM Service_Interruption__c WHERE Unit__r.Unit_Type__c IN: setUnitTypeIds AND Id NOT IN: lstServiceInterruptionIds AND Cancellation_Reason__c = Null];
        List<Unit_Type_Reservation__c> lstUnitTypeReservation = [SELECT Id, Start_Date__c, End_Date__c,Check_Out_Date__c, Unit__c, Unit_Type__c, Unit_Type__r.Units_Available__c FROM Unit_Type_Reservation__c WHERE Unit_Type__c In : setUnitTypeIds AND Status__c != 'Cancelled'];
        objTrCreateServiceInterruption.validateServiceInterruptionWithUnit(lstUnitIds, lstNewServiceInterruption, lstUnitTypeReservation, mapUnitIdsToUnitTypeId, lstOldServiceInterruption);
    	objTrCreateServiceInterruption.dateValidation(lstNewServiceInterruption,  mapOldRecords);
    }
}