Property Management System/force-app/main/default/objects/Service_Interruption__c/Service_Interruption__c.object-meta.xml
<CustomObject>
    <label>Service Interruption</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Interruption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Interruptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Completed</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Interruption_Reason__c.field-meta.xml
<CustomField>
    <fullName>Interruption_Reason__c</fullName>
    <label>Interruption Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Water Leakage</fullName>
            </value>
            <value>
                <fullName>Electricity Fitting</fullName>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Wiring</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Service Interruptions</relationshipLabel>
    <relationshipName>Service_Interruptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type__c/fields/Units_Available__c.field-meta.xml
<CustomField>
    <fullName>Units_Available__c</fullName>
    <label>Units Available</label>
    <summaryForeignKey>Unit__c.Unit_Type__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrCreateService_Interruption.cls
public with sharing class TrCreateService_Interruption implements Callable{
    public Object call(String action, Map<String, Object> mapOldAndNewRecords) {
        validateRecord( (List<sObject>)mapOldAndNewRecords.get('lstNewRecords') ,(Map<Id, sObject>)mapOldAndNewRecords.get('mapOldRecords'));
        return null;
    }
    public void validateRecord(List<Service_Interruption__c> lstNewServiceInterruption, map<id,sObject> mapOldServiceIT){
        List<Id> lstUnitIds = new List<Id>();        
        for(Service_Interruption__c serviceInterruptionRec : lstNewServiceInterruption){
            if(serviceInterruptionRec.Start_Date__c != NULL && serviceInterruptionRec.End_Date__c != NULL){
                  if(serviceInterruptionRec.Unit__c != NULL){
                       lstUnitIds.add(serviceInterruptionRec.Unit__c);
                     }
            } 
            else{
            	serviceInterruptionRec.addError('Please Check Start Date and End Date');
            }
            if (!String.isEmpty(serviceInterruptionRec.Interruption_Reason__c) && serviceInterruptionRec.Interruption_Reason__c.toLowerCase() != 'other'){
               // system.debug('other reason '+serviceInterruptionRec.Interruption_Reason__c.toLowerCase());
                serviceInterruptionRec.Other_Reason__c = null;
             }
        }
        Set<Id> setUnitTypeIds = new Set<Id>();
        List<Unit__c> lstUnitTypeIds = [SELECT Id, Unit_Type__c FROM Unit__c WHERE Id IN : lstUnitIds];
        Map<Id, Id> mapUnitIdsToUnitTypeId = new Map<Id, Id>();
        for(Unit__c objUnits: lstUnitTypeIds){
            setUnitTypeIds.add(objUnits.Unit_Type__c);
            mapUnitIdsToUnitTypeId.put(objUnits.Id, objUnits.Unit_Type__c);
        }
        List<Unit_Type_Reservation__c> lstUnitTypeReservation = [SELECT Id, Start_Date__c, End_Date__c, Check_Out_Date__c, Unit__c, Unit_Type__c, Unit_Type__r.Units_Available__c FROM Unit_Type_Reservation__c WHERE Unit_Type__c In : setUnitTypeIds AND Status__c != 'Cancelled'];
        List<Service_Interruption__c> lstOldServiceInterruption = [SELECT Id, Start_Date__c, End_Date__c, Unit__c, Unit__r.Unit_Type__c FROM Service_Interruption__c WHERE Unit__r.Unit_Type__c IN: setUnitTypeIds AND Cancellation_Reason__c = Null];
        validateServiceInterruptionWithUnit(lstUnitIds, lstNewServiceInterruption, lstUnitTypeReservation, mapUnitIdsToUnitTypeId, lstOldServiceInterruption);
    
    	dateValidation(lstNewServiceInterruption, mapOldServiceIT);
    }
    
    public void dateValidation(List<Service_Interruption__c> lstNewServiceInterruption,map<id,sObject> mapOldServiceIT){
        Set<String> strRecord = new Set<String>();
        for(Service_Interruption__c serviceInterruptionRec : lstNewServiceInterruption){
            if(serviceInterruptionRec.Start_Date__c != NULL && serviceInterruptionRec.End_Date__c != NULL ){
               
                if(serviceInterruptionRec.Start_Date__c < system.today()  ) {
                        if(mapOldServiceIT.containsKey(serviceInterruptionRec.Id) && serviceInterruptionRec.Start_Date__c != ((Service_Interruption__c)(mapOldServiceIT.get(serviceInterruptionRec.Id))).Start_Date__c){
                       serviceInterruptionRec.addError(System.Label.StartDateShouldBeGreaterThenOrEqualToTodayDate);
                    }
                    else if(! mapOldServiceIT.containsKey(serviceInterruptionRec.ID)){
                        serviceInterruptionRec.addError(System.Label.StartDateShouldBeGreaterThenOrEqualToTodayDate);
                    }else  if(serviceInterruptionRec.End_Date__c < system.today()){
                        serviceInterruptionRec.addError(System.label.EndDateShouldBeGreaterThanTodayDate);               
                    }

                }else if(serviceInterruptionRec.Start_Date__c >= serviceInterruptionRec.End_Date__c ){
                    serviceInterruptionRec.addError(System.label.EndDateShouldBeGreaterThenStartDate);
                }
                else{
                    if(serviceInterruptionRec.Unit__c != NULL){
                        String record = serviceInterruptionRec.Start_Date__c+'-'+serviceInterruptionRec.End_Date__c+'-'+serviceInterruptionRec.Unit__c;
                        if( strRecord.contains(record) ){
                            serviceInterruptionRec.addError(System.Label.DuplicateEntryFoundPleaseCheckDateAndUnit);
                        }
                        else{
                            strRecord.add(record); 
                        }
                    }
                }
            }
            else{
                serviceInterruptionRec.addError(System.Label.PleaseCheckStartDateAndEndDate);
            }
        }
    }
    
    public void  validateServiceInterruptionWithUnit(List<Id> lstUnitIds, List<Service_Interruption__c> lstNewItems, List<Unit_Type_Reservation__c> lstUnitTypeReservation, Map<Id, Id> mapUnitIdsToUnitTypeId, List<Service_Interruption__c> lstOldServiceInterruption){
        Map<Id, Map<Date, Integer>> mapUnitTypeIdToDateToCount = new Map<Id, Map<Date, Integer>>();
        Map<Id, Integer> mapUnitTypeIdToUnitAvailable = new Map<Id, Integer>();
        for(Service_Interruption__c serviceInterruption : lstNewItems){//new Service Interruption
            Integer daysBetween = serviceInterruption.Start_Date__c.daysBetween(serviceInterruption.End_Date__c);
            Id unitTypeId = mapUnitIdsToUnitTypeId.get(serviceInterruption.Unit__c);
            for(Integer i = 0; i < daysBetween; i++){
                if(!mapUnitTypeIdToDateToCount.isEmpty() && mapUnitTypeIdToDateToCount.containsKey(unitTypeId)){
                    mapUnitTypeIdToDateToCount.get(unitTypeId).put(serviceInterruption.Start_Date__c.addDays(i), 0);
                }else{
                    mapUnitTypeIdToDateToCount.put(unitTypeId, new Map<Date, Integer>{serviceInterruption.Start_Date__c.addDays(i) => 0});
                }
            }
            
            for(Unit_Type_Reservation__c unitTypeReservation:  lstUnitTypeReservation){
            	if(serviceInterruption.Unit__c == unitTypeReservation.Unit__c){
                    //Check new booking Start Date is in between service interruption record Start Date and End Date
                    if(unitTypeReservation.Start_Date__c <= serviceInterruption.Start_Date__c && 
                      ( (unitTypeReservation.Check_Out_Date__c == null) ? unitTypeReservation.End_Date__c : unitTypeReservation.Check_Out_Date__c) > serviceInterruption.Start_Date__c){
                        serviceInterruption.addError(System.Label.ReservationIsPresent);
                    }
                    //Check new booking End Date is in between service interruption record Start Date and End Date
                    else if(unitTypeReservation.Start_Date__c < serviceInterruption.End_Date__c && ((unitTypeReservation.Check_Out_Date__c == null) ? unitTypeReservation.End_Date__c : unitTypeReservation.Check_Out_Date__c) >= serviceInterruption.End_Date__c){
                        serviceInterruption.addError(System.Label.ReservationIsPresent);
                    }
                    //Check Service interruption Start Date is in between new booking record Start Date and End Date
                    else if(serviceInterruption.Start_Date__c <= unitTypeReservation.Start_Date__c && serviceInterruption.End_Date__c > unitTypeReservation.Start_Date__c){
                        serviceInterruption.addError(System.Label.ReservationIsPresent);
                    }
                }
                mapUnitTypeIdToUnitAvailable.put(unitTypeReservation.Unit_Type__c, (Integer)unitTypeReservation.Unit_Type__r.Units_Available__c);
                Integer daysBetweenOldStartAndEndDate = unitTypeReservation.Start_Date__c.daysBetween(unitTypeReservation.End_Date__c);
                for(Integer i = 0; i < daysBetweenOldStartAndEndDate; i++){
                    if(!mapUnitTypeIdToDateToCount.isEmpty() && mapUnitTypeIdToDateToCount.containsKey(unitTypeReservation.Unit_Type__c) && mapUnitTypeIdToDateToCount.get(unitTypeReservation.Unit_Type__c).containsKey(unitTypeReservation.Start_Date__c.addDays(i))){
                        Integer tempCount = (Integer)mapUnitTypeIdToDateToCount.get(unitTypeReservation.Unit_Type__c).get(unitTypeReservation.Start_Date__c.addDays(i));
                        mapUnitTypeIdToDateToCount.get(unitTypeReservation.Unit_Type__c).put(unitTypeReservation.Start_Date__c.addDays(i), ++tempCount);
                    }
                }
            }
            
            for(Service_Interruption__c objServiceInterruption: lstOldServiceInterruption){//Old Service Interruption
                Integer daysBetweenOldInterruptionStartAndEndDate = objServiceInterruption.Start_Date__c.daysBetween(objServiceInterruption.End_Date__c);
                for(Integer i = 0; i < daysBetweenOldInterruptionStartAndEndDate; i++){
                    if(!mapUnitTypeIdToDateToCount.isEmpty() && mapUnitTypeIdToDateToCount.containsKey(objServiceInterruption.Unit__r.Unit_Type__c) && mapUnitTypeIdToDateToCount.get(objServiceInterruption.Unit__r.Unit_Type__c).containsKey(objServiceInterruption.Start_Date__c.addDays(i))){
                        Integer tempCount = (Integer)mapUnitTypeIdToDateToCount.get(objServiceInterruption.Unit__r.Unit_Type__c).get(objServiceInterruption.Start_Date__c.addDays(i));
                        mapUnitTypeIdToDateToCount.get(objServiceInterruption.Unit__r.Unit_Type__c).put(objServiceInterruption.Start_Date__c.addDays(i), ++tempCount);
                    }
                }
                if(serviceInterruption.Unit__c != NULL && serviceInterruption.Unit__c == objServiceInterruption.Unit__c){
                    if(TrUTR_CreateAssignment.isWithinRange(objServiceInterruption.Start_Date__c, objServiceInterruption.End_Date__c, serviceInterruption.Start_Date__c) || 
                       TrUTR_CreateAssignment.isWithinRange(objServiceInterruption.Start_Date__c, objServiceInterruption.End_Date__c, serviceInterruption.End_Date__c)){
                           serviceInterruption.addError(System.Label.Interruption_is_already_reserved);
                       }else if(TrUTR_CreateAssignment.isWithinRange(serviceInterruption.Start_Date__c, serviceInterruption.End_Date__c, objServiceInterruption.Start_Date__c) || 
                                TrUTR_CreateAssignment.isWithinRange(serviceInterruption.Start_Date__c, serviceInterruption.End_Date__c, objServiceInterruption.End_Date__c)){
                                    serviceInterruption.addError(System.Label.Interruption_is_already_reserved);
                                }else if(serviceInterruption.Start_Date__c == objServiceInterruption.Start_Date__c && serviceInterruption.End_Date__c == objServiceInterruption.End_Date__c){
                                        serviceInterruption.addError(System.Label.Interruption_is_already_reserved);
                                    }
                }
            }
            
            for(Integer i = 0; i < daysBetween; i++){
                Integer currentCount = (mapUnitTypeIdToDateToCount.containsKey(unitTypeId) && mapUnitTypeIdToDateToCount.get(unitTypeId).containsKey(serviceInterruption.Start_Date__c.addDays(i))) ? mapUnitTypeIdToDateToCount.get(unitTypeId).get(serviceInterruption.Start_Date__c.addDays(i)) : Null;
                if(currentCount != Null && mapUnitTypeIdToUnitAvailable.get(unitTypeId) == currentCount){
                    serviceInterruption.addError('Unit is not available for Service Interruption');
                }
            }
        }
    }
}