Property Management System/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the type of Properties. Properties can be privately owned Home/House/Apt (Airbnb), 
Hotel/Motel/Inn, RV Resorts/Campgrounds</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Partially Checked In</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Unit Types</relationshipLabel>
    <relationshipName>Unit_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrReservationStatusUpdateonUTRTest.cls
@isTest
public with sharing class TrReservationStatusUpdateonUTRTest {
    @testSetup
    static void testSetup(){
        Property__c objOfProperty = TestDataFactory.createProperty();
        insert objOfProperty; 
        
        List<Unit_Type__c> lstOfUnitTypes = TestDataFactory.createUnitTypes(5);
        for(Unit_Type__c unitType : lstOfUnitTypes){
            unitType.Property__c = objOfProperty.Id;            
        }
        insert lstOfUnitTypes;
        
        
        List<Unit__c> lstOfUnits = new List<Unit__c>();
        for(Unit_Type__c unitType : lstOfUnitTypes){           
            lstOfUnits.addAll(TestDataFactory.createUnits(unitType, 5)); 
        }
        insert lstOfUnits;
        
        List<Contact> lstOfContacts = TestDataFactory.createContacts(2);
        
        insert lstOfContacts;
        
        List<Reservation__c> lstOfReservation = new List<Reservation__c>();
        for(Contact objOfContact : lstOfContacts){
            Reservation__c objOfReservation = TestDataFactory.createReservation(objOfContact.Id, objOfProperty.Id);
            lstOfReservation.add(objOfReservation);            
        }
        insert lstOfReservation;
        
        
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>();
        Unit_Type_Reservation__c objOfUnitTypeReservationCheck = TestDataFactory.createUnitTypeReservation(lstOfReservation[0].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[0].Id,lstOfUnits[0].Id,'Active','Make Reservation');
        lstUTR.add(objOfUnitTypeReservationCheck);
        Unit_Type_Reservation__c objOfUnitTypeReservationChkOut = TestDataFactory.createUnitTypeReservation(lstOfReservation[0].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[1].Id,lstOfUnits[1].Id,'Active','Make Reservation');
        lstUTR.add(objOfUnitTypeReservationChkOut);
        Unit_Type_Reservation__c objOfUnitTypeReservationCancel= TestDataFactory.createUnitTypeReservation(lstOfReservation[1].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[0].Id,lstOfUnits[2].Id,'Checked In','Check In');
        lstUTR.add(objOfUnitTypeReservationCancel);
        
        insert lstUTR;
        
        
    }
    @isTest
    static void UpdateResaftrUTRUpdate() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[1].Id];
        
        system.assertEquals(lstResData[0].Status__c!=null, true);
        List<Unit_Type_Reservation__c> lstUTRRec = new List<Unit_Type_Reservation__c>();
        for(Unit_Type_Reservation__c utrrecord:lstResData){
            
            
            utrrecord.Action__c='Check In';
            utrrecord.Status__c='Checked In';
            lstUTRRec.add(utrrecord) ;
            
        }
        update lstUTRRec;
        
    }
    @isTest
    static void UpdateResaftrUTRCheckedOut() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[1].Id ];
        List<Unit_Type_Reservation__c> lstUTRRecancel = new List<Unit_Type_Reservation__c>();
        for(Unit_Type_Reservation__c obUTR : lstResData )
        {
            obUTR.Action__c = 'Check Out';
            obUTR.Status__c='Checked Out';
            lstUTRRecancel.add(obUTR);
        }
        update lstUTRRecancel;
        system.assertEquals(lstUTRRecancel[0].Status__c=='Checked Out', true);
        
    }
    @isTest
    static void UpdateResaftrUTRCancelled() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[1].Id ];
        List<Unit_Type_Reservation__c> lstUTRRecancel = new List<Unit_Type_Reservation__c>();
        for(Unit_Type_Reservation__c obUTR : lstResData )
        {
            obUTR.Action__c = 'Cancel';
            obUTR.Status__c='Cancelled';
            lstUTRRecancel.add(obUTR);
        }
        update lstUTRRecancel;
        system.assertEquals(lstUTRRecancel[0].Status__c, 'Cancelled');
        
        
        
    }
    @isTest
    static void UpdateResaftrUTRForAll() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[0].Id ];
        
        
        
        lstResData[0].Action__c='Check Out';
        lstResData[0].Status__c='Checked Out';
        update lstResData[0];
        system.assertEquals(lstResData[0].Status__c, 'Checked Out');
        
        lstResData[1].Action__c='Cancel';
        lstResData[1].Status__c='Cancelled';
        
        update lstResData[1];
        
        
        
    }

    @isTest
    static void UpdateResaftrUTRPartCheck() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[0].Id ];
        
         
        
        lstResData[0].Action__c='Check In';
        lstResData[0].Status__c='Checked In';
        update lstResData[0];
        
        system.assertEquals(lstResData[0].Status__c, 'Checked In');
        
        
        
        
    }
    
    @isTest
    static void UpdateResaftrUTRActive() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[0].Id ];
        
        
        
        lstResData[0].Action__c='Make Reservation';
        lstResData[0].Status__c='Active';
        update lstResData[0];
        system.assertEquals(lstResData[0].Status__c, 'Active');
        
        
        
        
        
    }
    @isTest
    static void UpdateResaftrUTRCancelledANDCheckOut() {
        List<Reservation__c> lstReservationUPSRT = [Select Id From Reservation__c ];
        List<Unit_Type_Reservation__c> lstResData = [Select Id,Action__c,Status__c
                                                     From Unit_Type_Reservation__c  Where  Unit_Type_Reservation__c.Reservation__c =: lstReservationUPSRT[0].Id ];
        
        
        
        lstResData[0].Action__c='Check Out';
        lstResData[0].Status__c='Checked Out';
        update lstResData[0];
        
        
        lstResData[1].Action__c='Cancel';
        lstResData[1].Status__c='Cancelled';
        
        update lstResData[1];
          system.assertEquals(lstResData[1].Status__c, 'Cancelled');
        
        
    }
    
    
    
    
    
}