force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <type>TextArea</type>
</CustomField>

PMS/force-app/main/default/classes/InheritSharingTest.cls
@isTest
public class InheritSharingTest {
    
    @isTest()
	public static void testRunAs() {
        User u = [SELECT Id FROM User WHERE Id = '0052w000006NQ8L'];
        System.runAs(u) {
        	Student__c stud = new Student__c(Student_Name__c='testName');
			insert stud ;
			//then call the method
			Test.startTest();
			JobApexRecordWithoutSharing s=new JobApexRecordWithoutSharing();
 			s.getStudents();
            System.debug('success');
            Test.stopTest();
        }
    }
}