force-app/main/default/objects/Job_Rasika__c/Job_Rasika__c.object-meta.xml
<CustomObject>
    <label>Job_Rasika</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Jobs_Rasika Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs_Rasika</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Rasika__c/fields/Expires_On__c.field-meta.xml
<CustomField>
    <fullName>Expires_On__c</fullName>
    <description>This is a Date field which indicates the last date for applying for a job.</description>
    <label>Expires On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/JobScheduleApex.cls
public class JobScheduleApex implements Schedulable{
    
    public void execute(SchedulableContext sc){
        
        //Any code written in this method can be schedulled
        List<Job_Rasika__c> job = [SELECT id, Expires_On__c, Active__c FROM Job_Rasika__c WHERE Expires_On__c > Today AND Active__c = true];
        for(Job_Rasika__c jb: job){
            jb.Active__c = false;
        }
        UPDATE job;
        
        //Database.executeBatch(new JobScheduleBatch());
    }

}
//jobscheduler