force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Ending_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Ending_Mileage__c</fullName>
    <label>Ending Mileage</label>
    <precision>8</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Starting_Mile__c.field-meta.xml
<CustomField>
    <fullName>Starting_Mile__c</fullName>
    <label>Starting Mileage</label>
    <precision>8</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PMS/force-app/main/default/classes/TripTestSchedule.cls
@isTest
public class TripTestSchedule {
    
    //Test Methods
    @isTest static void inactiveTrip(){
        Date dt = Date.parse('9/27/2020');
        List<Trip__c> trp = new List<Trip__c>();
        Trip__c t = new Trip__c(Date__c = dt, Starting_Mile__c = 1, Ending_Mileage__c = 10, Description__c = 'test', Account__c='0012w00000MWvuK', Status__c = true);
        Trp.add(t);
        Test.startTest();
        try{
            insert Trp;
        }
        catch(Exception ee){}
        
    	Test.stopTest();
    }
}