Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check In Date</label>
    <type>Date</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the type of Properties. Properties can be privately owned Home/House/Apt (Airbnb), 
Hotel/Motel/Inn, RV Resorts/Campgrounds</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Reservation_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Member_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation- Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Partially Checked In</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Unit Types</relationshipLabel>
    <relationshipName>Unit_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Active_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Active_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Unit Type Reservations (Active Assignment)</relationshipLabel>
    <relationshipName>Unit_Type_Reservations1</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Member_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrAssignment_UpdtAsgmtAftrChkInTest.cls
@isTest
public with sharing class TrAssignment_UpdtAsgmtAftrChkInTest {
    @testSetup
    static void testSetup(){
        Test.startTest();
        Property__c objOfProperty = TestDataFactory.createProperty();
        insert objOfProperty; 
        
        List<Unit_Type__c> lstOfUnitTypes = TestDataFactory.createUnitTypes(5);
        for(Unit_Type__c unitType : lstOfUnitTypes){
            unitType.Property__c = objOfProperty.Id;            
        }
        insert lstOfUnitTypes;
        
        List<Unit__c> lstOfUnits = new List<Unit__c>();
        for(Unit_Type__c unitType : lstOfUnitTypes){           
            lstOfUnits.addAll(TestDataFactory.createUnits(unitType, 2)); 
        }
        insert lstOfUnits;
        
        List<Contact> lstOfContacts = TestDataFactory.createContacts(2);
        insert lstOfContacts;
        
        List<Reservation__c> lstOfReservation = new List<Reservation__c>();
        for(Contact objOfContact : lstOfContacts){
            Reservation__c objOfReservation = TestDataFactory.createReservation(objOfContact.Id, objOfProperty.Id);
            lstOfReservation.add(objOfReservation);            
        }
        insert lstOfReservation;
        
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>();
        Unit_Type_Reservation__c objOfUnitTypeReservation = TestDataFactory.createUnitTypeReservation(lstOfReservation[0].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[0].Id,lstOfUnits[0].Id,'Active','Make Reservation');
        lstUTR.add(objOfUnitTypeReservation);
        Unit_Type_Reservation__c objOfUnitTypeReservationChkOut = TestDataFactory.createUnitTypeReservation(lstOfReservation[1].Id, lstOfUnits[1].Unit_Type__c, lstOfContacts[1].Id,lstOfUnits[1].Id,'Active','Make Reservation');
        lstUTR.add(objOfUnitTypeReservationChkOut);
        insert lstUTR;
        
        
        List<Assignment__c> lstAssgnmnt = new List<Assignment__c>();
        Assignment__c AssgnmntChkIn = TestDataFactory.createAssignment(lstUTR[0].Id,lstUTR[0].Unit__c,lstUTR[0].Unit_Type__c,lstUTR[0].Reservation_Member_Name__c, 'Make Reservation');
        lstAssgnmnt.add(AssgnmntChkIn);
        Assignment__c AssgnmntChkOut = TestDataFactory.createAssignment(lstUTR[1].Id,lstUTR[1].Unit__c,lstUTR[0].Unit_Type__c,lstUTR[1].Reservation_Member_Name__c,'Check In');
        lstAssgnmnt.add(AssgnmntChkOut);
        
        insert lstAssgnmnt;
        
        lstUTR[1].Active_Assignment__c = lstAssgnmnt[1].Id;
        Upsert lstUTR;
        Test.stopTest();
    }
    @isTest 
    static void UpdateUTRandAssgnmntAftrChkIn(){
        Test.startTest();
        List<Assignment__c> lstAssgnmnts = new List<Assignment__c>([Select Id, Check_In_Date__c, Check_Out_Date__c, Unit_Type__c, Unit__c,Action__c, Unit_Type_Reservation__c
                                                                    From Assignment__c  Where Action__c = 'Make Reservation' Limit 10]);
        lstAssgnmnts[0].Action__c = 'Check In';
        
        Upsert lstAssgnmnts[0];
        system.assertEquals(lstAssgnmnts[0].Action__c,'Check In');      
        Test.stopTest();
    } 
    @isTest 
    static void UpdateUTRandAssgnmntAftrChkOut(){
        Test.startTest();
        List<Assignment__c> lstAssgnmnts = new List<Assignment__c>([Select Id, Check_In_Date__c, Check_Out_Date__c, Unit_Type__c, Unit__c,Action__c, Unit_Type_Reservation__c
                                                                    From Assignment__c Where Action__c ='Check In' Limit 10]);
        if(!lstAssgnmnts.isEmpty()){
            lstAssgnmnts[0].Action__c = 'Check Out';
            Unit_Type_Reservation__c objUnitTypeReservation = new Unit_Type_Reservation__c(Id = lstAssgnmnts[0].Unit_Type_Reservation__c, Active_Assignment__c = lstAssgnmnts[0].Id);
            Update objUnitTypeReservation;
            Upsert lstAssgnmnts[0];
            Assignment__c lstAssignment = [SELECT Id,Name, Unit_Type_Reservation__r.Status__c FROM Assignment__c WHERE Id = : lstAssgnmnts[0].Id limit 1];
            System.assert(lstAssignment.Unit_Type_Reservation__r.Status__c == 'Checked Out', 'Assignment not updated');
        }
        
        
    }
    
    @isTest 
    static void UpdateUTRandAssgnmntAftrChkInAssignAssg(){
        Test.startTest();
        List<Assignment__c> lstAssgnmnts = new List<Assignment__c>([Select Id, Check_In_Date__c, Check_Out_Date__c, Unit_Type__c, Unit__c,Action__c, Unit_Type_Reservation__c
                                                                    From Assignment__c  Where Action__c = 'Check In' Limit 10]);
        lstAssgnmnts[0].Action__c = 'Check In';
        Upsert lstAssgnmnts[0]  ;
        system.assertEquals(lstAssgnmnts[0].Action__c,'Check In');
        Test.stopTest();
    } 
        @isTest 
    static void UpdateUTRandAssgnmntAftrChkInAssgCheckIn(){
        Test.startTest();
        List<Assignment__c> lstAssgnmnts = new List<Assignment__c>([Select Id, Check_In_Date__c, Check_Out_Date__c, Unit_Type__c, Unit__c,Action__c, Unit_Type_Reservation__c
       
                                                                    From Assignment__c  Where Action__c = 'Make Reservation' Limit 10]);
        system.debug('lstAssgnmnts'+lstAssgnmnts);
        lstAssgnmnts[0].Action__c = 'Check In';
        lstAssgnmnts[0].Check_In_Date__c = System.today().adddays(2);
        Upsert lstAssgnmnts[0];
        
        system.assertEquals(lstAssgnmnts[0].Action__c,'Check In');
        Test.stopTest();
    } 
    
}