Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Service_Interruption__c/Service_Interruption__c.object-meta.xml
<CustomObject>
    <label>Service Interruption</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Interruption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Interruptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/Trigger_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Trigger configuration to run trigger classes</description>
    <label>TriggerConfiguration</label>
    <pluralLabel>TriggerConfiguration</pluralLabel>
</CustomObject>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class name to execute</description>
    <label>ClassName</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <description>Name of object for which you want to run this class</description>
    <inlineHelpText>Object Name</inlineHelpText>
    <label>ObjectApiName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PMS/force-app/main/default/classes/PostInstallPwrPMSTest.cls
@isTest
public class PostInstallPwrPMSTest {
	@isTest
    public static void testInstallScript() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        List<Sobject> lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c FROM Trigger_configuration__mdt');
        System.assert(lstTriggerConfig != null);
      }
     @isTest
    public static void createRecordtest() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
         PostInstallPwrPMS.createRecords();
        System.assert(customMetadata != null);
      }

    @isTest
    public static void createCustomMetadataRecord() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
         customMetadata = PostInstallPwrPMS.getCustomMetadataRecord('TrReservationUpdateUTROnCancel','TrReservationUpdateUTROnCancel',
                                                                                      'TrReservationUpdateUTROnCancel', 'AFTER_UPDATE', true, 'Reservation__c',
                                                                                      1);
        System.assert(customMetadata != null);
      }
    @isTest
    public static void createTriggerConfigurationRecordstest() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        List<sObject> lstRecordsToReturn = new List<sObject>();
       lstRecordsToReturn.add(PostInstallPwrPMS.creatTriggerConfigurationRecordForTest('TrReservationUpdateUTROnCancel', 'Reservation__c', 'BEFORE_UPDATE', '',1,'',true));
        system.assert(lstRecordsToReturn != null);
      }
          
     @isTest
    public static void getTriggerConfigurationRecordFortest() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        List<Sobject> lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c FROM Trigger_configuration__mdt');
        System.assert(lstTriggerConfig != null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        PostInstallPwrPMS.getTriggerConfigurationRecordForTest('Reservation__c',lstTriggerConfig);
        
      }   
           
     @isTest
    public static void getTriggerConfigurationRecordFortestassignment() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        List<Sobject> lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c FROM Trigger_configuration__mdt');
        System.assert(lstTriggerConfig != null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        PostInstallPwrPMS.getTriggerConfigurationRecordForTest('assignment__c',lstTriggerConfig);
        
      } 
      @isTest
    public static void getTriggerConfigurationRecordFortestserviceinterruption() {
       PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        List<Sobject> lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c FROM Trigger_configuration__mdt');
        System.assert(lstTriggerConfig != null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        PostInstallPwrPMS.getTriggerConfigurationRecordForTest('service_interruption__c',lstTriggerConfig);
        
      } 
      @isTest
    public static void getTriggerConfigurationRecordFortestunittypereservatio() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        List<Sobject> lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c FROM Trigger_configuration__mdt');
        System.assert(lstTriggerConfig != null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        PostInstallPwrPMS.getTriggerConfigurationRecordForTest('unit_type_reservation__c',lstTriggerConfig);
        
      }
       @isTest
    public static void getTriggerConfigurationRecordFortestunit() {
      PostInstallPwrPMS postinstall = new PostInstallPwrPMS();
        Test.testInstall(postinstall, null);
        List<Sobject> lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c FROM Trigger_configuration__mdt');
        System.assert(lstTriggerConfig != null);
        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
        PostInstallPwrPMS.getTriggerConfigurationRecordForTest('',lstTriggerConfig);
        
      }
          
    
}