Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check In Date</label>
    <type>Date</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Active_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Active_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Unit Type Reservations (Active Assignment)</relationshipLabel>
    <relationshipName>Unit_Type_Reservations1</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

PMS/force-app/main/default/classes/TrAssignment_CrtAsngmtAftrChkIn.cls
/************************************************************************************************************************************
Author 		: 	Poonam Jadhav
Description :   This apex class is used to update UTR after Chek In is done from table
History		:
**************************************************************************************************************************************/
public with sharing class TrAssignment_CrtAsngmtAftrChkIn  implements Callable{
    public TrAssignment_CrtAsngmtAftrChkIn() {
        
    }
    public Object call(String action, Map<String, Object> mapOldAndNewRecords) {
        if( ! ((List<sObject>)mapOldAndNewRecords.get('lstNewRecords')).isEmpty() ){
            createAssignmetRecord( (List<sObject>)mapOldAndNewRecords.get('lstNewRecords') );
        }
        return null;
    }

    public void createAssignmetRecord(List<Assignment__c> lstAssgnmnt){
        Map<Id,Assignment__c> mapassgnmnt = new Map<Id,Assignment__c>(lstAssgnmnt);
        set<Id> setUTRId = new set<Id>();
        for(Assignment__c assgnmnt : mapassgnmnt.values() ){
            if(assgnmnt.Action__c == 'Check In' && assgnmnt.Unit_Type_Reservation__c != null){
                setUTRId.add(assgnmnt.Unit_Type_Reservation__c);
            }
        }
        if(!setUTRId.isEmpty()){ 
            map<Id,Unit_Type_Reservation__c> mapUTRToUpdate = new map<Id,Unit_Type_Reservation__c> ([SELECT Id, Status__c, Active_Assignment__c FROM Unit_Type_Reservation__c
                                                                                                     Where Id IN: setUTRId]);
            if(!mapUTRToUpdate.isEmpty()){
                for(Assignment__c assgnmnt : mapassgnmnt.values() ){
                    mapUTRToUpdate.get(assgnmnt.Unit_Type_Reservation__c).Active_Assignment__c = assgnmnt.Id;
                    mapUTRToUpdate.get(assgnmnt.Unit_Type_Reservation__c).Status__c = 'Checked In';
                    mapUTRToUpdate.get(assgnmnt.Unit_Type_Reservation__c).Unit__c = assgnmnt.Unit__c ;
                    mapUTRToUpdate.get(assgnmnt.Unit_Type_Reservation__c).Action__c = assgnmnt.Action__c ;
                    mapUTRToUpdate.get(assgnmnt.Unit_Type_Reservation__c).Check_In_Date__c = Date.today();
                }
                try{
                    update mapUTRToUpdate.values();
                }
                catch(Exception ex){
                    lstAssgnmnt[0].addError(ex.getMessage());
                }
            }
        }
    }
}