Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the type of Properties. Properties can be privately owned Home/House/Apt (Airbnb), 
Hotel/Motel/Inn, RV Resorts/Campgrounds</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Reservation_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Member_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation- Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Partially Checked In</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/Service_Interruption__c.object-meta.xml
<CustomObject>
    <label>Service Interruption</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Interruption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Interruptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Completed</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Service Interruptions</relationshipLabel>
    <relationshipName>Service_Interruptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Unit Types</relationshipLabel>
    <relationshipName>Unit_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Active_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Active_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Unit Type Reservations (Active Assignment)</relationshipLabel>
    <relationshipName>Unit_Type_Reservations1</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Member_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrUTR_UpdateAssignmntAfterUTRUpdateTest.cls
@isTest
public with sharing class TrUTR_UpdateAssignmntAfterUTRUpdateTest {
    @testSetup
    static void testSetup(){
        Property__c objOfProperty = TestDataFactory.createProperty();
        insert objOfProperty; 
        
        List<Unit_Type__c> lstOfUnitTypes = TestDataFactory.createUnitTypes(5);
        for(Unit_Type__c unitType : lstOfUnitTypes){
            unitType.Property__c = objOfProperty.Id;            
        }
        insert lstOfUnitTypes;
        
        List<Unit__c> lstOfUnits = new List<Unit__c>();
        for(Unit_Type__c unitType : lstOfUnitTypes){           
            lstOfUnits.addAll(TestDataFactory.createUnits(unitType, 2)); 
        }
        insert lstOfUnits;
        
        List<Contact> lstOfContacts = TestDataFactory.createContacts(2);
        insert lstOfContacts;
        
        List<Reservation__c> lstOfReservation = new List<Reservation__c>();
        for(Contact objOfContact : lstOfContacts){
            Reservation__c objOfReservation = TestDataFactory.createReservation(objOfContact.Id, objOfProperty.Id);
            lstOfReservation.add(objOfReservation);            
        }
        insert lstOfReservation;
        
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>();
        Unit_Type_Reservation__c objOfUnitTypeReservation = TestDataFactory.createUnitTypeReservation(lstOfReservation[0].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[0].Id,lstOfUnits[0].Id,'Active','Make Reservation');
        objOfUnitTypeReservation.Start_Date__c = system.today().addDays(8);
        objOfUnitTypeReservation.End_Date__c = system.today().addDays(9);
        lstUTR.add(objOfUnitTypeReservation); 
        Unit_Type_Reservation__c objOfUTRChkIn = TestDataFactory.createUnitTypeReservation(lstOfReservation[0].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[0].Id,lstOfUnits[0].Id,'Checked In','Check In');
        lstUTR.add(objOfUTRChkIn);
        insert lstUTR;
        
        
        List<Assignment__c> lstAssgnmnt = new List<Assignment__c>();
        Assignment__c AssgnmntChkIn = TestDataFactory.createAssignment(lstUTR[0].Id,lstUTR[0].Unit__c,lstUTR[0].Unit_Type__c,lstUTR[0].Reservation_Member_Name__c, 'Make Reservation');
        lstAssgnmnt.add(AssgnmntChkIn);
        Assignment__c AssgnmntChkOut = TestDataFactory.createAssignment(lstUTR[0].Id,lstUTR[0].Unit__c,lstUTR[0].Unit_Type__c,lstUTR[0].Reservation_Member_Name__c,'Check In');
        lstAssgnmnt.add(AssgnmntChkOut);
        insert lstAssgnmnt;
        
        lstUTR[0].Active_Assignment__c = lstAssgnmnt[0].Id;
        lstUTR[1].Active_Assignment__c = null;
        upsert lstUTR;
    }
    @isTest
    static void UpdtUTRChngUnt(){
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c ,Active_Assignment__c
                                                                                    from Unit_Type_Reservation__c where Action__c = 'Make Reservation' AND Active_Assignment__c != null ]);
        set<Id> setUntTypId = new set<Id>();
        setUntTypId.add(lstUTR[0].Unit_Type__c);
        List<Unit__c> lstUnt =  new List<Unit__c>([Select id from Unit__c where Unit_Type__c IN :setUntTypId]);
        lstUTR[0].Action__c = 'Update Reservation';
        lstUTR[0].Unit__c = lstUnt[1].Id;
        Upsert lstUTR;
        List<Assignment__c> lstAssgnmnt = new  List<Assignment__c>([Select id,Unit__c,Check_Out_Date__c from Assignment__c  where Id =: lstUTR[0].Active_Assignment__c ] );
        System.assert(lstUTR[0].Unit__c == lstAssgnmnt[0].Unit__c );
        
    } 
    @isTest
    static void UpdtUTRChngUntAftrChkIn(){
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,Active_Assignment__c 
                                                                                    from Unit_Type_Reservation__c where Status__c = 'Checked In' ]);
        set<Id> setUntTypId = new set<Id>();
        setUntTypId.add(lstUTR[0].Unit_Type__c);
        List<Unit__c> lstUnt =  new List<Unit__c>([Select id from Unit__c where Unit_Type__c IN :setUntTypId]);
        lstUTR[0].Action__c = 'Update Reservation';
        lstUTR[0].Unit__c = lstUnt[1].Id;
        Upsert lstUTR;
        List<Unit_Type_Reservation__c> lstUTRAftrUdt = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,Active_Assignment__c 
                                                                                           from Unit_Type_Reservation__c where Id =: lstUTR[0].Id ]);
        List<Assignment__c> lstAssgnmnt = new  List<Assignment__c>([Select id,Unit__c,Check_Out_Date__c from Assignment__c  where Id =: lstUTRAftrUdt[0].Active_Assignment__c ] );
        System.assert(lstUTR[0].Unit__c == lstAssgnmnt[0].Unit__c );
    } 
    @isTest 
    static void UpdtAnyFldofUTR(){
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,End_Date__c,Active_Assignment__c
                                                                                    from Unit_Type_Reservation__c where  Active_Assignment__c != null ]);
        lstUTR[0].Action__c = 'Update Reservation';
        lstUTR[0].End_Date__c = ((Date)lstUTR[0].End_Date__c).addDays(1);
        Upsert lstUTR;
        List<Unit_Type_Reservation__c> lstUTRAftrUdt = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,Active_Assignment__c 
                                                                                           from Unit_Type_Reservation__c where Id =: lstUTR[0].Id ]);
        List<Assignment__c> lstAssgnmnt = new  List<Assignment__c>([Select id,Unit__c,Check_Out_Date__c from Assignment__c where Id =: lstUTRAftrUdt[0].Active_Assignment__c] );
        System.assert(lstUTRAftrUdt[0].Unit__c == lstAssgnmnt[0].Unit__c );
        
    }
    @isTest
    static void canclResrvatn(){
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c, Start_Date__c, End_Date__c ,Active_Assignment__c
                                                                                    from Unit_Type_Reservation__c where Status__c = 'Active' ]);
        
        lstUTR[0].Action__c = 'Cancel Reservation';
        lstUTR[0].Cancellation_Reason__c='Death';
        lstUTR[0].Start_Date__c = system.today().addDays(7);
        lstUTR[0].End_Date__c = system.today().addDays(8);
        Upsert lstUTR;
        
        List<Assignment__c> lstAssgnmnt = new  List<Assignment__c>([Select id,Action__c from Assignment__c where Id =: lstUTR[0].Active_Assignment__c] );
        System.assert( lstAssgnmnt[0].Action__c == 'Cancel Reservation' );
    }
    @isTest 
    static void canclResrvatnError(){
        try{
            List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,End_Date__c 
                                                                                        from Unit_Type_Reservation__c where Status__c = 'Checked In' ]);
            lstUTR[0].Action__c = 'Cancel Reservation';
            Upsert lstUTR;
        }
        catch(Exception ex){
            System.AssertNotEquals(ex.getMessage().contains('Cannot Cancel Reservation'), true); 
        }
    } 
    @isTest
    static void extndResrvatn(){
        List<Unit_Type_Reservation__c> lstUTR1 = new List<Unit_Type_Reservation__c>([Select id,Status__c, End_Date__c, Unit_Type__c, Unit__c
                                                                                     from Unit_Type_Reservation__c]);
        delete lstUTR1[1];
        
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,End_Date__c,Active_Assignment__c 
                                                                                    from Unit_Type_Reservation__c where Status__c = 'Active' ]);
        lstUTR[0].Action__c = 'Change Reservation';
        lstUTR[0].End_Date__c = ((Date)lstUTR[0].End_Date__c).addDays(1);
        Upsert lstUTR;
        List<Assignment__c> lstAssgnmnt = new  List<Assignment__c>([Select id,Check_Out_Date__c from Assignment__c where Id =: lstUTR[0].Active_Assignment__c] );
        System.assert(lstUTR[0].End_Date__c == lstAssgnmnt[0].Check_Out_Date__c );
    } 
    @isTest
    static void extndResrvatnError(){
        try{
            List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,End_Date__c 
                                                                                        from Unit_Type_Reservation__c where Status__c = 'Active' ]);
            lstUTR[0].Action__c = 'Change Reservation';
            Upsert lstUTR;
            
        }
        catch(Exception ex){
            
            System.AssertEquals(ex.getMessage().contains('Cannot Change the Reservation. Please select valid date'), true);
        }
    }
    
    @isTest
    static void ChangeResrvatnError(){
        try{
            List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c,End_Date__c 
                                                                                        from Unit_Type_Reservation__c where Status__c = 'Active' ]);
            lstUTR[0].Action__c = 'Change Reservation';
            lstUTR[0].End_Date__c = Date.today();
            Upsert lstUTR;
            
        }
        catch(Exception ex){
            
            System.AssertEquals(ex.getMessage().contains('Cannot Change the Reservation. Please select valid date'), false);
        }
    }
    
      @isTest
    static void UpdtUTRChngUntwthSIUnit(){
        List <Service_Interruption__c> lstServiceI =new List<Service_Interruption__c>([SELECT Id, Start_Date__c, End_Date__c, Unit__c FROM Service_Interruption__c ]);
        system.debug('lstServiceI'+lstServiceI);
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>([Select id,Action__c,Unit_Type__c, Unit__c ,Active_Assignment__c
                                                                                    from Unit_Type_Reservation__c where Action__c = 'Make Reservation' AND Active_Assignment__c != null ]);
        system.debug('lstUTR'+lstUTR);
        set<Id> setUntTypId = new set<Id>();
        setUntTypId.add(lstUTR[0].Unit_Type__c);
        List<Unit__c> lstUnt =  new List<Unit__c>([Select id from Unit__c where Unit_Type__c IN :setUntTypId]);
        lstUTR[0].Action__c = 'Update Reservation';
        lstUTR[0].Unit__c = lstUnt[1].Id;
        Upsert lstUTR;
        List<Assignment__c> lstAssgnmnt = new  List<Assignment__c>([Select id,Unit__c,Check_Out_Date__c from Assignment__c  where Id =: lstUTR[0].Active_Assignment__c ] );
        System.assert(lstUTR[0].Unit__c == lstAssgnmnt[0].Unit__c );
        
    }
    
}