Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Active_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Active_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Unit Type Reservations (Active Assignment)</relationshipLabel>
    <relationshipName>Unit_Type_Reservations1</relationshipName>
    <type>Lookup</type>
</CustomField>

PMS Demo/force-app/main/default/classes/TrUTR_UpdateAssignmntAfterUTRInsrt.cls
/************************************************************************************************************************************
Author 		: 	Poonam Jadhav
Description :   This apex class is used to update Unit_Type_Reservation__c field of Assignment with respective UTR Id after UTR insert.
History		:
**************************************************************************************************************************************/
public with sharing class 	TrUTR_UpdateAssignmntAfterUTRInsrt implements Callable{
    
    public Object call(String action, Map<String, Object> mapOldAndNewRecords) {
        if( ! ((List<sObject>)mapOldAndNewRecords.get('lstNewRecords')).isEmpty() ){
            updateAssignmetRecord( (List<sObject>)mapOldAndNewRecords.get('lstNewRecords') );
        }
        return null;
    }
    
    // Update Assignmnet record of respective UTR with UTR Id in Unit_Type_Reservation__c field
    public void updateAssignmetRecord(List<Unit_Type_Reservation__c> lstUTR){
        set<Id> setUTRId = new set<Id>();
        for(Unit_Type_Reservation__c utr : lstUTR){
            setUTRId.add(utr.Active_Assignment__c);
        }
        map<Id,Assignment__c> mapAssngmnt = new map<Id,Assignment__c>([Select  Unit_Type_Reservation__c from Assignment__c 
                                                                       where Id IN: setUTRId]);
        
        for(Unit_Type_Reservation__c utr : lstUTR){
            if(utr.Action__c == 'Make Reservation'){
                if(mapAssngmnt.containsKey(utr.Active_Assignment__c)){
                    mapAssngmnt.get(utr.Active_Assignment__c).Unit_Type_Reservation__c =  utr.Id;
                }
            }
        }  
        update mapAssngmnt.values();
    }
}