Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Check_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Date__c</fullName>
    <label>Check In Date</label>
    <type>Date</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Check_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Out_Date__c</fullName>
    <label>Check Out Date</label>
    <type>Date</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Active_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Active_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Assignment</label>
    <referenceTo>Assignment__c</referenceTo>
    <relationshipLabel>Unit Type Reservations (Active Assignment)</relationshipLabel>
    <relationshipName>Unit_Type_Reservations1</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

PMS Demo/force-app/main/default/classes/TrAssignment_UpdtAsgmtAftrChkIn.cls
/************************************************************************************************************************************
Author 		: 	Poonam Jadhav
Description :   This apex class is used to update UTR after Chek In and Check Out is done from Grid.
History		:
**************************************************************************************************************************************/
public with sharing class TrAssignment_UpdtAsgmtAftrChkIn implements Callable{
    
    public Object call(String action, Map<String, Object> mapOldAndNewRecords) {
        if( ! ((List<sObject>)mapOldAndNewRecords.get('lstNewRecords')).isEmpty() ){
            updateAssignmentAndUTR( (List<sObject>)mapOldAndNewRecords.get('lstNewRecords'), (Map<Id, sObject>)mapOldAndNewRecords.get('mapOldRecords') );
        }
        return null;
    }
    
    public void updateAssignmentAndUTR(List<Assignment__c> lstAssgnment ,Map<Id, SObject> mapOldAssgnmnt){
        map<Id,Assignment__c> mapAssgnmnt = new map<Id,Assignment__c> (lstAssgnment);
        map<Id, Unit_Type_Reservation__c> mapUTR = new map<Id, Unit_Type_Reservation__c>([SELECT Id, Start_Date__c,Check_Out_Date__c,Check_In_Date__c, Status__c,End_Date__c,Action__c FROM Unit_Type_Reservation__c Where Active_Assignment__c IN: mapAssgnmnt.keySet()]);
        Boolean isUTRUpdate = false;
        for(Assignment__c assgmnt : lstAssgnment ){
            if(assgmnt.Unit_Type_Reservation__c != NULL && mapUTR.get(assgmnt.Unit_Type_Reservation__c) != NULL && assgmnt.Action__c == 'Check In'){
                if(assgmnt.Check_In_Date__c >= mapUTR.get(assgmnt.Unit_Type_Reservation__c).Start_Date__c){
                    mapUTR.get(assgmnt.Unit_Type_Reservation__c).Status__c = 'Checked In' ;
                    mapUTR.get(assgmnt.Unit_Type_Reservation__c).Unit__c = assgmnt.Unit__c;
                    mapUTR.get(assgmnt.Unit_Type_Reservation__c).Action__c = assgmnt.Action__c;
                    mapUTR.get(assgmnt.Unit_Type_Reservation__c).Check_In_Date__c = Date.today();
                    isUTRUpdate = true;
                }
                else {
                    assgmnt.addError('Error while Check In, Please check respective record for Unit Type Reservation ', false);
                }
            }
            if(assgmnt.Action__c == 'Check Out'  ){ //&& ((Assignment__c)mapOldAssgnmnt.get(assgmnt.Id)).Action__c == 'Check In')
                if( mapUTR.get(assgmnt.Unit_Type_Reservation__c).Check_In_Date__c == Date.today()) {
                    assgmnt.Check_Out_Date__c = Date.today() + 1;
                    mapUTR.get(assgmnt.Unit_Type_Reservation__c).Check_Out_Date__c = Date.today() +1;
                }
                else{
                    assgmnt.Check_Out_Date__c = Date.today() ;
                    mapUTR.get(assgmnt.Unit_Type_Reservation__c).Check_Out_Date__c = Date.today();
                }
                mapUTR.get(assgmnt.Unit_Type_Reservation__c).Status__c = 'Checked Out' ;
                mapUTR.get(assgmnt.Unit_Type_Reservation__c).Action__c = assgmnt.Action__c ;
                isUTRUpdate = true;
            }
        }
        if(isUTRUpdate){
            try{
                update mapUTR.values();
            }catch(Exception ex){
                lstAssgnment[0].addError(ex.getMessage());
            }
        }
        
    }
}