Property Management System/force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignment Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Assignment__c/fields/Unit_Type_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Reservation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Type Reservation</label>
    <referenceTo>Unit_Type_Reservation__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the type of Properties. Properties can be privately owned Home/House/Apt (Airbnb), 
Hotel/Motel/Inn, RV Resorts/Campgrounds</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>This object will store all the reservations which will be made from Grid.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RSVN-{0000}</displayFormat>
        <label>Reservation Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Other_Reason__c.field-meta.xml
<CustomField>
    <fullName>Other_Reason__c</fullName>
    <label>Other Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Property Management System/force-app/main/default/objects/Reservation__c/fields/Reservation_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Member_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation- Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/Service_Interruption__c.object-meta.xml
<CustomObject>
    <label>Service Interruption</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Interruption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Interruptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Completed</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Interruption_Reason__c.field-meta.xml
<CustomField>
    <fullName>Interruption_Reason__c</fullName>
    <label>Interruption Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Painting</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Water Leakage</fullName>
            </value>
            <value>
                <fullName>Electricity Fitting</fullName>
            </value>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Wiring</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Service_Interruption__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Service Interruptions</relationshipLabel>
    <relationshipName>Service_Interruptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Unit_Type__c.Property__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Property__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type__c/Unit_Type__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the various types of Unit Types.</description>
    <label>Unit Type</label>
    <nameField>
        <label>Unit Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Unit Types</relationshipLabel>
    <relationshipName>Unit_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/Unit_Type_Reservation__c.object-meta.xml
<CustomObject>
    <label>Unit Type Reservation</label>
    <nameField>
        <displayFormat>UTR-{0000}</displayFormat>
        <label>Unit Reservation Type Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Illness</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Weather</fullName>
            </value>
            <value>
                <fullName>Change in Plan</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation__c.field-meta.xml
<CustomField>
    <fullName>Reservation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation</label>
    <referenceTo>Reservation__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Reservation_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Member_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reservation Member Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/objects/Unit_Type_Reservation__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Type</label>
    <referenceTo>Unit_Type__c</referenceTo>
    <relationshipLabel>Unit Type Reservations</relationshipLabel>
    <relationshipName>Unit_Type_Reservations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Property Management System/force-app/main/default/classes/TrUpdateService_InterruptionTest.cls
@isTest
public class TrUpdateService_InterruptionTest {
	@testSetup
    static void testSetup(){
        Property__c objOfProperty = TestDataFactory.createProperty();
        insert objOfProperty; 
        
        List<Unit_Type__c> lstOfUnitTypes = TestDataFactory.createUnitTypes(5);
        for(Unit_Type__c unitType : lstOfUnitTypes){
            unitType.Property__c = objOfProperty.Id;            
        }
        insert lstOfUnitTypes;
        
        List<Unit__c> lstOfUnits = new List<Unit__c>();
        for(Unit_Type__c unitType : lstOfUnitTypes){           
            lstOfUnits.addAll(TestDataFactory.createUnits(unitType, 2)); 
        }
        insert lstOfUnits;
        
        List<Contact> lstOfContacts = TestDataFactory.createContacts(2);
        insert lstOfContacts;
        
        List<Reservation__c> lstOfReservation = new List<Reservation__c>();
        for(Contact objOfContact : lstOfContacts){
            Reservation__c objOfReservation = TestDataFactory.createReservation(objOfContact.Id, objOfProperty.Id);
            lstOfReservation.add(objOfReservation);            
        }
        insert lstOfReservation;
        
        List<Unit_Type_Reservation__c> lstUTR = new List<Unit_Type_Reservation__c>();
        Unit_Type_Reservation__c objOfUnitTypeReservation = TestDataFactory.createUnitTypeReservation(lstOfReservation[0].Id, lstOfUnits[0].Unit_Type__c, lstOfContacts[0].Id,lstOfUnits[0].Id,'Active','Make Reservation');
        lstUTR.add(objOfUnitTypeReservation);
        insert lstUTR;
        
        
        List<Assignment__c> lstAssgnmnt = new List<Assignment__c>();
        Assignment__c AssgnmntChkIn = TestDataFactory.createAssignment(lstUTR[0].Id,lstUTR[0].Unit__c,lstUTR[0].Unit_Type__c,lstUTR[0].Reservation_Member_Name__c, 'Make Reservation');
        lstAssgnmnt.add(AssgnmntChkIn);
        insert lstAssgnmnt;
        Service_Interruption__c objServiceInterruption = new Service_Interruption__c(
            Start_Date__c = system.today().addDays(8),
            End_Date__c = system.today().addDays(9), 
            Unit__c = lstOfUnits[0].Id,
         Interruption_Reason__c = 'Repair'); 
        insert objServiceInterruption;
       Service_Interruption__c objServiceInterruption1 = new Service_Interruption__c(
            Start_Date__c = system.today().addDays(10),
            End_Date__c = system.today().addDays(11), 
            Unit__c = lstOfUnits[0].Id,
           Interruption_Reason__c = 'Other',
             Other_Reason__c = 'Test'); 
        insert objServiceInterruption1;        
        
        
        
    }
    @isTest 
    static void createAndUpdateServiceInterruption(){
        List<Service_Interruption__c> lstServiceInterruption = [SELECT Id,Unit__c FROM Service_Interruption__c];
        Service_Interruption__c objServiceInterruption1 = new Service_Interruption__c(Start_Date__c = system.today().addDays(9), End_Date__c = system.today().addDays(10), Unit__c = lstServiceInterruption[0].Unit__c,Interruption_Reason__c= 'Repair');
        insert objServiceInterruption1;
        System.assert(objServiceInterruption1.Id != NULL, 'Service Interruption Failed to Save');
        /*update objServiceInterruption1;
        System.assert(objServiceInterruption1.Id != NULL, 'Service Interruption Failed to Save');*/

    }
        @isTest 
    static void UpdateServiceInterruptionCancellationReason(){
        Test.startTest();
        List<Service_Interruption__c> lstServiceInterruption = [SELECT Id,Unit__c,Cancellation_Reason__c,Action__c,Interruption_Reason__c FROM Service_Interruption__c where Interruption_Reason__c != Null];
        
        lstServiceInterruption[0].Action__c = 'Cancel Interruption';
        lstServiceInterruption[0].Cancellation_Reason__c = null;
        try{
         update lstServiceInterruption[0];
           }catch(Exception Ex){
             
           System.AssertEquals(Ex.getMessage().contains('Cant cancel service interruption without cancellation reason'), true);
        }
          Test.stopTest();

    }
     @isTest 
    static void UpdateServiceInterruptionOtherReason(){
        Test.startTest();
       List<Service_Interruption__c> lstServiceInterruption = [SELECT Id,Unit__c,Interruption_Reason__c,Other_Reason__c FROM Service_Interruption__c where Interruption_Reason__c =: 'other'];
       system.assert(lstServiceInterruption[0].Interruption_Reason__c != Null);
       lstServiceInterruption[0].Interruption_Reason__c = 'Painting';
       update lstServiceInterruption[0];
       
       system.assert(lstServiceInterruption[0].Interruption_Reason__c != null);
          Test.stopTest();

    }
       @isTest 
    static void createAndUpdateServiceInterruptionError(){
        List<Service_Interruption__c> lstServiceInterruption = [SELECT Id,Unit__c FROM Service_Interruption__c];
        Service_Interruption__c objServiceInterruption1 = new Service_Interruption__c(Start_Date__c = system.today().addDays(9), End_Date__c = system.today().addDays(10), Unit__c = lstServiceInterruption[0].Unit__c);
        try{        insert objServiceInterruption1;
           }
        catch(Exception Ex)
        {
            System.AssertEquals(Ex.getMessage().contains('End Date should be greater then Start Date'), false);
           
           
        }
         objServiceInterruption1.End_Date__c =   system.today().addDays(5)    ;  
        
        try{       
            update objServiceInterruption1;
           }
        catch(Exception Ex)
        {
            System.AssertEquals(Ex.getMessage().contains('End Date should be greater then Start Date'), false);
           
           
        }

    }
    @isTest 
    static void UpdateServiceInterruptionEnddate(){
        Test.startTest();
       List<Service_Interruption__c> lstServiceInterruption = [SELECT Id,Unit__c,Interruption_Reason__c,Other_Reason__c,End_Date__c FROM Service_Interruption__c];
      
       lstServiceInterruption[0].End_Date__c = system.today().addDays(-2);
       
        try{
             update lstServiceInterruption[0];
        }catch(Exception Ex)
        {
             System.AssertEquals(Ex.getMessage().contains('End Date should be greater than Today’s Date.'), false);
            
        }
        Test.stopTest();
  }
}