Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/Trigger_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Trigger configuration to run trigger classes</description>
    <label>TriggerConfiguration</label>
    <pluralLabel>TriggerConfiguration</pluralLabel>
</CustomObject>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class name to execute</description>
    <label>ClassName</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>EventType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFTER_INSERT</fullName>
                <default>true</default>
                <label>AFTER_INSERT</label>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>BEFORE_INSERT</fullName>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Turn ON and OFF trigger classes</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <description>Name of object for which you want to run this class</description>
    <inlineHelpText>Object Name</inlineHelpText>
    <label>ObjectApiName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Record_Types_API_Names__c.field-meta.xml
<CustomField>
    <fullName>Record_Types_API_Names__c</fullName>
    <description>Record types for which this class should execute</description>
    <label>RecordTypesAPINames</label>
    <type>TextArea</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/Recursion_times__c.field-meta.xml
<CustomField>
    <fullName>Recursion_times__c</fullName>
    <defaultValue>ABS(1)</defaultValue>
    <label>Recursion_times</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <label>SortOrder</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Property Management System/force-app/main/default/objects/Trigger_Configuration__mdt/fields/UpdatedFields__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFields__c</fullName>
    <label>UpdatedFields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Property Management System/force-app/main/default/classes/TriggerManager.cls
/************************************************************************************************************************************
Author 		: 	Enzigma Software Pvt LTD.
Description :   Standard class to manage all trigger classes.
History		:
----------------------------------------------------------------------------------------------------------------------------------
VERSION		DATE				AUTHOR					       DETAIL
1	 	05/02/2019			Enzigma Software Pvt LTD.
**************************************************************************************************************************************/
public with sharing class TriggerManager {
    
    public static Map <String, Map<String, List<CustomBusinessProcess>>> mapBusinessProcesses = new Map <String, Map<String, List<CustomBusinessProcess>>>();
    
    public static void execute(String strObjectName) {
        strObjectName = strObjectName.toLowerCase();
        System.debug('In TriggerManager Trigger.operationType---'+strObjectName);
        System.debug('In TriggerManager Trigger.operationType---'+Trigger.operationType);
        List<CustomBusinessProcess> lstBusinessProcesses = getBusinessProcesses(strObjectName, String.valueOf(Trigger.operationType));
        if(lstBusinessProcesses != null) {
            for(CustomBusinessProcess process : lstBusinessProcesses) {
                process.execute();
            }
        }
    }
    
    /*********************************************************************************************************************************
        Description  :   This method will create an object according to every Custom Metadata type and returns the List of CustomBusinessProcess .
    *********************************************************************************************************************************/
    public static List<CustomBusinessProcess> getBusinessProcesses(String strObjectName, String operationType) {
        if(!mapBusinessProcesses.containsKey(strObjectName)) {
            Map<String, List<CustomBusinessProcess>> mapEventProcessess = new Map<String, List<CustomBusinessProcess>>();
             List<sObject> lstTriggerConfig = new List<sObject> ();
            if(!Test.isRunningTest()) {
               
               lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c, SortOrder__c, Event_Type__c,  Record_Types_API_Names__c, Recursion_times__c, UpdatedFields__c FROM Trigger_configuration__mdt WHERE Object_API_Name__c LIKE: strObjectName AND Is_Active__c = true ORDER BY SortOrder__c') ; 
            } else {
                lstTriggerConfig = Database.query('SELECT Class_Name__c, Object_API_Name__c, SortOrder__c, Event_Type__c, Record_Types_API_Names__c, Recursion_times__c, UpdatedFields__c FROM Trigger_configuration__mdt WHERE Object_API_Name__c LIKE: strObjectName ORDER BY SortOrder__c');
            }
            if(Test.isRunningTest()){
				System.debug('here :: isRunningTest');
                lstTriggerConfig = PostInstallPwrPMS.getTriggerConfigurationRecordForTest(strObjectName, lstTriggerConfig);
            }
            if(lstTriggerConfig!= null) {
                List<CustomBusinessProcess> lstBusinessProcesses;                
                for(sObject triggerConfig : lstTriggerConfig) {
                    if(mapEventProcessess.containsKey((String)triggerConfig.get('Event_Type__c'))){
                        lstBusinessProcesses = mapEventProcessess.get((String)triggerConfig.get('Event_Type__c'));
                    }else{
                        lstBusinessProcesses = new List<CustomBusinessProcess>();
                    }
                   lstBusinessProcesses.add(new CustomBusinessProcess(triggerConfig));
                    mapEventProcessess.put((String)triggerConfig.get('Event_Type__c'), lstBusinessProcesses);
                }
                mapBusinessProcesses.put(strObjectName, mapEventProcessess); 
            }
        }
        return mapBusinessProcesses.get(strObjectName).get(operationType);
    }
}